### ISSUE TITLE
performance problem

### ISSUE THREAD

**Issue by osadrac** [shashstormer/m3u8_proxy-cors#9]
The lib worked very well, but I have a performance problem, a direct request to the website with m3u8 takes 200ms, a request to fastapi takes 3000ms+, when it doesn't cancel, with small traffic it works well. Are there any changes to release better performance?

![image](https://github.com/shashstormer/m3u8_proxy-cors/assets/23412947/f1033cb7-74e4-4f17-a743-df2fc71cd88a)

**Comment by shashstormer** [comment]
There is a possibility that the hosting device or did not have sufficient bandwidth, but it is possible that the response times may reduce by using streaming response available in FastAPI but there is no garuntee, the server actually has about 10-200ms delay than the actual site. If you are speaking about flixhq then i have heard people say that setting some headers improves the speed. The server is capable of handling large traffic too as for some reason i had 3 million requests over a week and did not face any issues or longer times you may test https://cros.shashstorm.in (this deployment has a bug and doesn't give m3u8 with https:// in the start due to dns and hosting service ssl it will be fixed soon)

**Comment by osadrac** [comment]
Initially I also thought it could be the server. So I hosted my website and Proxy locally, this ping was already a local request, I realized that it takes around 200ms in the same location, with another 200ms of the stream I want to play it would give 400/500ms. It wouldn't be a big deal, there's something strange that I don't understand. even the website and the localhost proxy I still have 3000ms+. with just one player it works very well. But when I add the second player, there's already a big delay, I'm going to test what you sent me and see if I can find something with fastapi. If you are interested in helping a little more. my discord is maverick5772

**Comment by osadrac** [comment]
It also returns several cancellations, I couldn't understand why, I'm analyzing it to find out why it was cancelled.

![Captura de tela 2024-02-14 182046](https://github.com/shashstormer/m3u8_proxy-cors/assets/23412947/55ad5695-8a64-48c6-aa56-9272d2da4645)
